AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: AWS SAM template for the AWS::SES::MailManagerAddonSubscription resource type

Globals:
  Function:
    Timeout: 180  # docker start-up times can be long for SAM CLI
    MemorySize: 256

Resources:
  TypeFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.ses.mailmanageraddonsubscription.HandlerWrapper::handleRequest
      Runtime: java17
      CodeUri: ./target/aws-ses-mailmanageraddonsubscription-handler-1.0-SNAPSHOT.jar

  TestEntrypoint:
    Type: AWS::Serverless::Function
    Properties:
      Handler: software.amazon.ses.mailmanageraddonsubscription.HandlerWrapper::testEntrypoint
      Runtime: java17
      CodeUri: ./target/aws-ses-mailmanageraddonsubscription-handler-1.0-SNAPSHOT.jar
